<a href="https://colab.research.google.com/github/RafsanJany-44/IQ-RAM-SIRSK/blob/main/MEGA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("/content/drive/MyDrive/Iqram Sir/Tinnitus_ALR_features_106.csv")

# New Section

In [3]:
dataset.head(5)

Subject Type/Class Test Type Gap duration  n0_gap_peak_ms  p1_gap_peak_ms  \
0            Healthy      Test         20ms             101             147   
1            Healthy      Test         20ms             132             155   
2            Healthy      Test         20ms             107             160   
3            Healthy      Test         20ms              77             200   
4            Healthy      Test         20ms             153             128   

   n1_gap_peak_ms  p2_gap_peak_ms  n2_gap_peak_ms  p3_gap_peak_ms  \
0             214             263             366             105   
1             217             301             383             131   
2             221             305             396             128   
3             233             268             379             166   
4             224             264             337             147   

   n0_nogap_peak_ms  ...  gap_auc_n1p2n2_by_total  gap_auc_p2n2p3_by_total  \
0               149  ...                20.751953                 0.038292   
1               175  ...                21.972656                 0.118686   
2               192  ...                18.310547                 0.048787   
3               120  ...                16.357422                 0.062302   
4               176  ...                16.845703                 0.100706   

   nogap_auc_total  nogap_auc_total_abs  nogap_auc_n0p1n1_by_total  \
0        33.935547            15.285080                  10.327331   
1        35.644531            15.548298                  10.137840   
2        41.015625            13.078348                   8.643543   
3        39.306641             7.087050                   5.196947   
4        32.958984            15.198039                  11.166206   

   nogap_auc_p1n1p2_by_total  nogap_auc_n1p2n2_by_total  \
0                   1.672325                  86.663602   
1                   3.010325                  79.939031   
2                   2.167986                  48.851014   
3                   3.325309                  47.181061   
4                   2.334388                  45.697755   

   nogap_auc_p2n2p3_by_total  fft_gap_total_auc  fft_nogap_total_auc  
0                   1.333714           0.940225             0.074033  
1                   1.775618           0.665121             0.227634  
2                   1.769573           0.618907             0.093239  
3                   0.831445           0.453683             0.119996  
4                   1.665048           0.845292             0.192855  

[5 rows x 109 columns]

In [4]:
dataset.iloc[:, 0].value_counts()

Healthy     172
Tinnitus    158
Name: Subject Type/Class, dtype: int64

In [5]:
X = dataset.iloc[:, 3:]
y = dataset.iloc[:, 0]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#GradientBoosting Classifier

In [8]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold

classifier = GradientBoostingClassifier(n_estimators=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 4 23]]
              precision    recall  f1-score   support

     Healthy       0.89      0.79      0.84        39
    Tinnitus       0.74      0.85      0.79        27

    accuracy                           0.82        66
   macro avg       0.81      0.82      0.82        66
weighted avg       0.83      0.82      0.82        66

Accurecy:  0.8181818181818182


#Random Forest Classifier

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=18,max_depth=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[32  7]
 [ 7 20]]
              precision    recall  f1-score   support

     Healthy       0.82      0.82      0.82        39
    Tinnitus       0.74      0.74      0.74        27

    accuracy                           0.79        66
   macro avg       0.78      0.78      0.78        66
weighted avg       0.79      0.79      0.79        66

Accurecy:  0.7878787878787878


#Ada Boost Classifier

In [10]:
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(n_estimators=54,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[35  4]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.80      0.90      0.84        39
    Tinnitus       0.82      0.67      0.73        27

    accuracy                           0.80        66
   macro avg       0.81      0.78      0.79        66
weighted avg       0.80      0.80      0.80        66

Accurecy:  0.803030303030303


#XG

In [11]:


import xgboost as xgb
xgb_classifier = xgb.XGBClassifier(max_depth=3,random_state=0)
xgb_classifier.fit(X_train,y_train)
y_pred = xgb_classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[32  7]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.78      0.82      0.80        39
    Tinnitus       0.72      0.67      0.69        27

    accuracy                           0.76        66
   macro avg       0.75      0.74      0.75        66
weighted avg       0.76      0.76      0.76        66

Accurecy:  0.7575757575757576


#KNN

In [12]:
from sklearn.neighbors import KNeighborsClassifier
KNN_class = KNeighborsClassifier(n_neighbors=164)
KNN_class.fit(X_train, y_train)
y_pred=KNN_class.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[39  0]
 [19  8]]
              precision    recall  f1-score   support

     Healthy       0.67      1.00      0.80        39
    Tinnitus       1.00      0.30      0.46        27

    accuracy                           0.71        66
   macro avg       0.84      0.65      0.63        66
weighted avg       0.81      0.71      0.66        66

Accurecy:  0.7121212121212122


#With Synthetic Data

**GradientBoosting**

NON RANDOM

In [13]:

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier


X, y = make_classification(random_state=0)

model_5 = GradientBoostingClassifier(n_estimators=9,max_depth=3,random_state=0)

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

n_scores = cross_val_score(model_5, X, y, scoring='accuracy', cv=cv)

print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Mean Accuracy: 0.883 (0.097)


Random

In [14]:

from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import GradientBoostingClassifier

X, y = make_classification(random_state=1)

model_5 = GradientBoostingClassifier(n_estimators=9,max_depth=3,random_state=0)

cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)

n_scores = cross_val_score(model_5, X, y, scoring='accuracy', cv=cv)

print('Mean Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Mean Accuracy: 0.953 (0.050)


#USING SMOTE

In [15]:
X = dataset.iloc[:, 3:]
y = dataset.iloc[:, 0]


from sklearn.model_selection import train_test_split
  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
  

In [16]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state = 2)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

**Gradient Boosting**

In [17]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RepeatedStratifiedKFold

classifier = GradientBoostingClassifier(n_estimators=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 4 23]]
              precision    recall  f1-score   support

     Healthy       0.89      0.79      0.84        39
    Tinnitus       0.74      0.85      0.79        27

    accuracy                           0.82        66
   macro avg       0.81      0.82      0.82        66
weighted avg       0.83      0.82      0.82        66

Accurecy:  0.8181818181818182


**Random Forest**

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=18,max_depth=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[31  8]
 [ 7 20]]
              precision    recall  f1-score   support

     Healthy       0.82      0.79      0.81        39
    Tinnitus       0.71      0.74      0.73        27

    accuracy                           0.77        66
   macro avg       0.77      0.77      0.77        66
weighted avg       0.77      0.77      0.77        66

Accurecy:  0.7727272727272727


**Ada Boosting**

In [19]:
from sklearn.ensemble import AdaBoostClassifier 

classifier = AdaBoostClassifier(n_estimators=54,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))
print("Accurecy: ",accuracy_score(y_test, y_pred))

[[35  4]
 [ 9 18]]
              precision    recall  f1-score   support

     Healthy       0.80      0.90      0.84        39
    Tinnitus       0.82      0.67      0.73        27

    accuracy                           0.80        66
   macro avg       0.81      0.78      0.79        66
weighted avg       0.80      0.80      0.80        66

Accurecy:  0.803030303030303


#SHAP Explanation


In [21]:
!pip install shap

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [23]:
import shap

In [24]:
def Global(classifier, X_test_,features_names, max_display=5):

  explainer = shap.Explainer(classifier.predict, X_test)

  shap_values = explainer( X_test)

  shap.summary_plot(shap_values, X, plot_type="bar",max_display=max_display,feature_names=features_names)

  shap.plots.bar(shap_values,max_display=5)

  shap.summary_plot(shap_values,max_display=max_display,feature_names=features_names)

  return shap_values


def single_shape_row(classifier,features_names,shap_index=0):
  explainer = shap.Explainer(classifier.predict, X_test)

  shap_values = explainer( X_test)

  shap.plots.waterfall(shap_values[shap_index])

  shap.initjs()
  shap.plots.force(shap_values[shap_index],feature_names=features_names)



def part_wise(classifier, X_train, features_names, max_display=5, shap_index=0, start_index=1, end_index=2):

  explainer = shap.KernelExplainer(classifier.predict_proba, X_train)

  shap_values = explainer.shap_values(X_test[start_index:end_index])


  shap.initjs()
  # Force plot
  prediction = classifier.predict(X_test[start_index:end_index])[0]
  print(f"The  predicted: {prediction}")
  shap.force_plot(explainer.expected_value[shap_index],
                  shap_values[shap_index],
                  X_test[start_index:end_index],feature_names=features_names)

  shap.summary_plot(shap_values, X_test[start_index:end_index], plot_type="bar",class_names=['Healthy','Tinnitus'],max_display=max_display,feature_names=features_names)





In [26]:
features_names=list(dataset.iloc[0:0, 3:])
print(features_names)



['n0_gap_peak_ms', 'p1_gap_peak_ms', 'n1_gap_peak_ms', 'p2_gap_peak_ms', 'n2_gap_peak_ms', 'p3_gap_peak_ms', 'n0_nogap_peak_ms', 'p1_nogap_peak_ms', 'n1_nogap_peak_ms', 'p2_nogap_peak_ms', 'n2_nogap_peak_ms', 'p3_nogap_peak_ms', 'n0p1_interval_gap', 'n0n1_interval_gap', 'n0p2_interval_gap', 'n0n2_interval_gap', 'n0p3_interval_gap', 'p1n1_interval_gap', 'p1p2_interval_gap', 'p1n2_interval_gap', 'p1p3_interval_gap', 'n1p2_interval_gap', 'n1n2_interval_gap', 'n1p3_interval_gap', 'p2n2_interval_gap', 'p2p3_interval_gap', 'n2p3_interval_gap', 'n0p1_interval_nogap', 'n0n1_interval_nogap', 'n0p2_interval_nogap', 'n0n2_interval_nogap', 'n0p3_interval_nogap', 'p1n1_interval_nogap', 'p1p2_interval_nogap', 'p1n2_interval_nogap', 'p1p3_interval_nogap', 'n1p2_interval_nogap', 'n1n2_interval_nogap', 'n1p3_interval_nogap', 'p2n2_interval_nogap', 'p2p3_interval_nogap', 'n2p3_interval_nogap', 'n0_gap_peak_amp', 'p1_gap_peak_amp', 'n1_gap_peak_amp', 'p2_gap_peak_amp', 'n2_gap_peak_amp', 'p3_gap_peak_amp

In [28]:
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.preprocessing import LabelEncoder
classifier = GradientBoostingClassifier(n_estimators=4,random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
encoder=LabelEncoder()
dataset["Subject Type/Class"]=encoder.fit_transform(dataset["Subject Type/Class"])

Global(classifier, X_train,features_names,10)

ValueError: ignored